[package]
name = "unlim-clout-desktop"
version = "0.1.0"
description = "Unlimited Cloud Storage Powered by Telegram"
authors = ["Awais Khan"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
